apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: global-dynamic
spec:
  selector:
    gateway-service: app
  type: LoadBalancer
  externalIPs:
  - 157.90.31.191
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: http