apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-deployment
  namespace: global-dynamic
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # how many pods we can add at a time
      maxUnavailable: 1  # maxUnavailable define how many pods can be unavailable during the rolling update
  selector:
    matchLabels:
      logger-service: app
  template:
    metadata:
      labels:
        logger-service: app
    spec:
      containers:
        - image: ganiipek/global-dynamic-logger-service:latest
          name: logger-dp
          imagePullPolicy: Always
          env: 
          - name: SECRET_DB_HOST
            valueFrom:
              secretKeyRef:
                name: global-dynamic-mongodb
                key: host
          - name: SECRET_DB_PORT
            valueFrom:
              secretKeyRef:
                name: global-dynamic-mongodb
                key: port
          - name: SECRET_DB_USER
            valueFrom:
              secretKeyRef:
                name: global-dynamic-mongodb
                key: user
          - name: SECRET_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: global-dynamic-mongodb
                key: password
          - name: SECRET_DB_VHOST
            valueFrom:
              secretKeyRef:
                name: global-dynamic-mongodb
                key: vhost
          - name: SECRET_RABBITMQ_HOST
            valueFrom:
              secretKeyRef:
                name: global-dynamic-rabbitmq
                key: host
          - name: SECRET_RABBITMQ_PORT
            valueFrom:
              secretKeyRef:
                name: global-dynamic-rabbitmq
                key: port
          - name: SECRET_RABBITMQ_USERNAME
            valueFrom:
              secretKeyRef:
                name: global-dynamic-rabbitmq
                key: username
          - name: SECRET_RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: global-dynamic-rabbitmq
                key: password
          - name: SECRET_RABBITMQ_VHOST
            valueFrom:
              secretKeyRef:
                name: global-dynamic-rabbitmq
                key: vhost
          
      imagePullSecrets:
        - name: regcred